# Generated by Django 5.2.7 on 2026-01-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text_content',
            field=models.TextField(blank=True, help_text='Текст книги для режиму читання', null=True),
        ),
    ]
