# Generated by Django 5.2.7 on 2026-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bookrating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва (для адміна)')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Банер')),
                ('url', models.URLField(verbose_name='Куди веде посилання')),
                ('location', models.CharField(choices=[('catalog', 'У каталозі (між книгами)'), ('details', 'Сторінка книги (під кнопкою Оренди)')], default='catalog', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рекламний банер',
                'verbose_name_plural': 'Рекламні банери',
            },
        ),
    ]
